Fix basic auth with encoded characters (#3815)
spring-cloud/spring-cloud-netflix pull request #4260
Opened 2024-02-19 21:43 UTC by ZIRAKrezovic

See: #3815

2024-03-25 15:43 UTC, OlgaMaciaszek requested changes
Hello @ZIRAKrezovic, thanks for creating the PR. Please add a test. Please add your full name and surname with `@author` tag to the javadoc of any classes you've modified.

2024-03-26 09:52 UTC, ZIRAKrezovic commented
Hi @OlgaMaciaszek, I have added a test. Although I'm not sure if it's the right approach, or if it can be done with unit tests without a server, it tests what this fix is supposed to fix.

2024-03-27 08:39 UTC, ZIRAKrezovic commented
I have found out how Spring Webflux developers do the tests and updated my test accordingly.

https://github.com/spring-projects/spring-framework/blob/6.1.x/spring-webflux/src/test/java/org/springframework/web/reactive/function/client/DefaultWebClientTests.java#L128

2024-04-02 14:50 UTC, OlgaMaciaszek requested changes
Thanks @ZIRAKrezovic. Looks good. Have just added comments about some cosmetic issues. Please fix.

2024-04-02 14:50 UTC, OlgaMaciaszek commented on spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/http/WebClientTransportClientFactoryTest.java
> +import org.mockito.ArgumentCaptor;
Please update the year in the license comment.

2024-04-02 14:50 UTC, OlgaMaciaszek commented on spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/http/WebClientTransportClientFactoryTest.java
> +		given(exchangeFunction.exchange(captor.capture())).willReturn(Mono.just(mockResponse));
It's a good approach. On a higher level, you could possibly also use `okhttp3.mockwebserver.MockWebServer` to record and verify the response, but the way you've mocked it is good.

2024-04-02 14:50 UTC, OlgaMaciaszek commented on spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/http/WebClientTransportClientFactoryTest.java
> +				() -> WebClient.builder().exchangeFunction(this.exchangeFunction));
Please remove unnecessary `this` keyword.

2024-04-03 10:33 UTC, OlgaMaciaszek approved these changes
Thanks @ZIRAKrezovic. LGTM.

2024-04-03 10:38 UTC, merged