Add support for configuring RestTemplate via RestTemplateBuilder (#4255)
spring-cloud/spring-cloud-netflix pull request #4262
Opened 2024-02-19 22:32 UTC by ZIRAKrezovic

Fixes: #4255

2024-03-26 16:56 UTC, OlgaMaciaszek requested changes
Thanks, @ZIRAKrezovic. This looks good. Please just address the comment about the javadoc and licensce changes in the classes you've edited.

2024-03-26 16:56 UTC, OlgaMaciaszek commented on spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/config/DiscoveryClientOptionalArgsConfiguration.java
> +			EurekaClientHttpRequestFactorySupplier eurekaClientHttpRequestFactorySupplier,
Please add your full name and surname with `@author` tag to the javadoc of all the files you've modified. Please update the year in the license comments of the files you've modified.

2024-03-26 17:38 UTC, OlgaMaciaszek commented on spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/config/DiscoveryClientOptionalArgsConfiguration.java
> +			EurekaClientHttpRequestFactorySupplier eurekaClientHttpRequestFactorySupplier,
@ZIRAKrezovic Actually, I'm just going to do it for you, since I'd like to make sure we include this in the upcoming release.

2024-03-26 17:42 UTC, OlgaMaciaszek approved these changes

2024-03-26 17:42 UTC, merged

2024-03-26 17:57 UTC, ZIRAKrezovic commented
Thanks!

2024-03-26 18:24 UTC, OlgaMaciaszek commented
Did it, but the changes cause test failures (for some reason, the build was apparently not triggered on your PR). Will revert them - please resubmit your PR with fixed tests.

2024-03-26 18:28 UTC, OlgaMaciaszek commented
@ZIRAKrezovic - see details: https://github.com/spring-cloud/spring-cloud-netflix/actions/runs/8440522374/job/23117589376. Some tests will need updating to the new API.

2024-03-26 18:44 UTC, ZIRAKrezovic commented
Hi @OlgaMaciaszek. I did a rebase, applied your patch that fixes the copyright year and author, and fixed the compilation of the failed test.

2024-04-02 13:27 UTC, OlgaMaciaszek commented
Thanks @ZIRAKrezovic .